"""Calculate when the forecasted utilization will breach a warning threshold.

The module loads a forecast generated by forecast_engine.py, detects the first
point where utilization crosses the configured threshold, computes the lead time
relative to the current data point, and derives a confidence score from the width
of the uncertainty interval.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


def load_forecast(csv_path: str | Path | None = None) -> pd.DataFrame:
    """Load the forecast CSV produced by forecast_engine.py."""
    if csv_path is None:
        csv_path = Path(__file__).resolve().parent / "output" / "forecast.csv"

    forecast = pd.read_csv(csv_path, parse_dates=["ds"])
    forecast = forecast.sort_values("ds").reset_index(drop=True)
    return forecast


def calculate_impact(
    forecast: pd.DataFrame,
    threshold: float = 90.0,
    now_time: pd.Timestamp | None = None,
) -> dict:
    """Return a structured alert payload for the predicted breach."""
    if now_time is None:
        now_time = forecast["ds"].iloc[0]

    breach_row = None
    for _, row in forecast.iterrows():
        if row["yhat"] >= threshold:
            breach_row = row
            break

    if breach_row is None:
        raise ValueError("Forecast never crosses the configured threshold.")

    breach_time = pd.Timestamp(breach_row["ds"])
    lead_time_minutes = int((breach_time - now_time).total_seconds() // 60)

    uncertainty_width = max(0.0, float(breach_row["yhat_upper"]) - float(breach_row["yhat_lower"]))
    confidence_score = max(0.0, min(0.99, 1 - (uncertainty_width / 80)))

    if lead_time_minutes < 0:
        lead_time_minutes = 0

    trend_change = round(float(breach_row["yhat"]) - float(forecast["yhat"].iloc[0]), 1)

    alert = {
        "predicted_issue": "Interface congestion — hub-spoke link",
        "confidence_score": round(confidence_score, 2),
        "time_to_impact": f"{lead_time_minutes} minutes",
        "affected_scope": "Branch site to Hub",
        "current_trend": f"utilization rising {trend_change}%/interval",
    }
    return alert


def main() -> None:
    """Load the forecast and print the calculated impact summary."""
    base_dir = Path(__file__).resolve().parent
    forecast = load_forecast(base_dir / "output" / "forecast.csv")
    alert = calculate_impact(forecast)

    output_path = base_dir / "output" / "prediction_alert.json"
    output_path.write_text(json.dumps(alert, indent=2), encoding="utf-8")

    print(json.dumps(alert, indent=2))
    print(f"Saved alert to {output_path}")


if __name__ == "__main__":
    main()
